hardware:
server:
  distributionDirectory: ../../frontend/dist
  ovenProgramFolder: ./programs
  port: 3333
  testRampTimeMinutes: 200
  testRampTemperature: 1000
oven:
  length: 0.11
  height: 0.08
  width: 0.23
  insulationWidths: [0.075, 0.05]
  thermalConductivities: [0.3, 0.14]
  thermalCapacity: 900
  weight: 24
  maxPower: 1000
controller:
  kpRamp: 0.9
  kiRamp: 0.001
  kdRamp: 0.001
  kpMaintain: 0.01
  kiMaintain: 0.0001
  kdMaintain: 0.0001
  stepTime: 1
  saveTime: 60
  savedRunFolder: ./runs
